services:
  backend:
    build: ./backend
    container_name: lms-backend
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - media_data:/app/media
      - db_data:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_data &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2"

  frontend:
    build: ./frontend
    container_name: lms-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  media_data:
  db_data:
